target 'RegiaAnglorum' do
    use_frameworks!
    pod "HockeySDK"
    pod 'ReactNativeSearchBar', :path => '../node_modules/react-native-search-bar'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end